#!/bin/bash

# Setup script for GitHub Pages deployment
# This script helps you configure your frontend for GitHub Pages

echo "🚀 GitHub Pages Deployment Setup"
echo "================================"
echo ""

# Check if we're in the right directory
if [ ! -f "frontend/package.json" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

echo "✅ Project structure verified"
echo ""

# Check if Vercel URL is provided
if [ -z "$1" ]; then
    echo "📝 Usage: ./setup-github-pages.sh <your-vercel-url>"
    echo ""
    echo "Example:"
    echo "  ./setup-github-pages.sh https://toronto-stupid-hackathon.vercel.app"
    echo ""
    echo "⚠️  You need to deploy to Vercel first to get your backend URL!"
    echo ""
    echo "Steps:"
    echo "  1. Deploy backend to Vercel: https://vercel.com/new"
    echo "  2. Copy your Vercel URL"
    echo "  3. Run this script with that URL"
    exit 1
fi

VERCEL_URL="$1"

# Remove trailing slash if present
VERCEL_URL="${VERCEL_URL%/}"

echo "📦 Creating production environment file..."

# Create .env.production
cat > frontend/.env.production << EOF
# Production API URL (Vercel backend)
# Generated by setup-github-pages.sh
VITE_API_URL=${VERCEL_URL}
EOF

echo "✅ Created frontend/.env.production"
echo ""
echo "🎯 Configuration complete!"
echo ""
echo "Next steps:"
echo "  1. Commit and push your changes:"
echo "     git add ."
echo "     git commit -m \"Configure GitHub Pages deployment\""
echo "     git push origin main"
echo ""
echo "  2. Enable GitHub Pages:"
echo "     - Go to: Settings → Pages"
echo "     - Source: GitHub Actions"
echo "     - Click Save"
echo ""
echo "  3. Your site will be live at:"
echo "     https://sophian098.github.io/TorontoStupidHackathon/"
echo ""
echo "✨ Done!"
